title = "A FOF"
description = "按权重组合虚拟基金"
frequency = "1y"

# 回测使用选项 -A 0.3

[funds]
high-momentum = 5
high-real-cash = 1
low-pb = 5
permanent = 1
small-cap = 5

[search]
frequency = ["3m", "6m", "1y"]

[search.funds]
high-momentum = [1, 2, 3, 5]
high-real-cash = [1, 2, 3, 5]
low-pb = [1, 2, 3, 5]
permanent = [1, 2, 3, 5]
small-cap = [1, 2, 3, 5]
