title = "持有多因子评分最高的ETF"

tickers = [
  "510300", # 沪深300ETF
  "159949", # 创业板50ETF
  "513100", # 纳斯达克100ETF
  "513500", # 标普500ETF
  "518880", # 黄金ETF
  "511260", # 十年国债ETF
  "161715", # 大宗商品LOF
]

[[rules]]
name = "hold_top_factors_score"
frequency = "2w"

[rules.options]
limit = 3
lookback_trade_days = 21
weight_max_drawdown = 4.0
weight_momentum = 0.0
weight_sharpe = 1.0
weight_volatility = 5.0

[rules.search]
limit = [3, 4]
lookback_trade_days = [21, 28]
weight_max_drawdown = [3.0, 4.0, 5.0]
weight_momentum = [0.0, 1.0]
weight_sharpe = [0.0, 1.0, 2.0]
weight_volatility = [4.0, 5.0, 6.0]
