title = "高动量"
description = "持有动量最高的ETF"

tickers = [
  "159593",  # 中证A50ETF
  "159338",  # 中证A500ETF
  "159949",  # 创业板50ETF
  "159758",  # 红利质量ETF
  "159263",  # 价值ETF
  "159222",  # 自由现金流ETF
  "510900",  # 恒生H股ETF
  "513180",  # 恒生科技ETF
  "513100",  # 纳斯达克100ETF
  "513500",  # 标普500ETF
  "511260",  # 十年国债ETF
  "511180",  # 可转债ETF
  "518880",  # 黄金ETF
  "516650",  # 有色金属ETF
  "162411",  # 华宝油气LOF
  "159985",  # 豆粕期货ETF
  "512800",  # 银行ETF
  # "515210",  # 钢铁ETF
  # "515220",  # 煤炭ETF
  # "159870",  # 化工ETF
  # "512200",  # 房地产ETF
]

[[rules]]
name = "hold_by_momentum"
frequency = "1m"

[rules.options]
deviation_weight = 0.6
efficiency_weight = 0.4
limit = 2
lookback_trade_days = 250
ma_period = 21
regression_r2_adjust = false
weight_method = "filter_max(0.9)"

[rules.search]
# frequency = ["2w", "3w", "1m", "2m", "3m", "4m"]

[rules.search.options]
# deviation_weight = [0, 0.2, 0.4, 0.6, 0.8, 1]
# efficiency_weight = [0, 0.2, 0.4, 0.6, 0.8, 1]
# limit = [1, 2, 3, 4, 5]
# lookback_trade_days = [21, 63, 125, 250, 375, 500]
# ma_period = [10, 21, 42, 63, 125]
# regression_r2_adjust = [true, false]
# weight_method = [
#   "equal",
#   "grad(1.2)",
#   "grad(1.5)",
#   "grad(2)",
#   "filter_max(0.9)",
#   "filter_max(0.8)",
#   "filter_max(0.7)",
#   "filter_max(0.6)",
#   "filter_max(0.5)",
# ]

[[rules]]
name = "resize_by_spike"
frequency = "1d"

[rules.options]
spike_days = 3
spike_fall_threshold = 0.04
spike_rise_threshold = 0.08

[rules.search.options]
# spike_days = [1, 2, 3, 5]
# spike_fall_threshold = [0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.08, 0.1, 0.12, 0.15, 0.2]
# spike_rise_threshold = [0.03, 0.04, 0.05, 0.06, 0.08, 0.1, 0.12, 0.15, 0.2, 1]
