title = "高质量现金"
description = "持有股息率和自由现金流高的股票"

[[ticker_sources]]
source = "000015.CSI"  # 上证红利
source_type = "index"

[[ticker_sources]]
source = "000922.CSI"  # 中证红利100
source_type = "index"

[[ticker_sources]]
source = "399324.CNI"  # 深证红利
source_type = "index"

[[ticker_sources]]
source = "399411.CNI"  # 国证红利100
source_type = "index"

[[ticker_sources]]
source = "932365.CSI"  # 中证全指自由现金流
source_type = "index"

[[ticker_sources]]
source = "980092.CNI"  # 国证自由现金流
source_type = "index"

[[rules]]
name = "hold_by_real_cash"
frequency = "2m"

[rules.options]
adjust_dividend_ratio_weight = 0
adjust_momentum_weight = 1.2
adjust_volatility_weight = 0.2
cash_ratio_quantile_lower = 0.2
current_ratio_quantile_lower = 0
dividend_ratio_quantile_lower = 0.6
exclude_sectors = [
  # 金融地产
  "银行",
  "非银金融",
  "房地产",

  # 强周期
  "煤炭",
  "钢铁",
  "有色金属",
  "石油石化",

  # 低质低效
  "综合",
  "公用事业",
]
limit = 2
lookback_trade_days = 250
roe_quantile_lower = 0.3
roe_years = 3
skip_same_sector = true
weight_method = "filter_max(0.7)"

[rules.search]
# frequency = ["1m", "2m", "3m", "6m"]

[rules.search.options]
# adjust_dividend_ratio_weight = [0, 0.2, 0.4, 0.6]
# adjust_momentum_weight = [0, 0.2, 0.4, 0.6, 0.8, 1, 1.2, 1.4, 1.6]
# adjust_volatility_weight = [0, 0.2, 0.4, 0.6]
# cash_ratio_quantile_lower = [0, 0.1, 0.2, 0.3]
# current_ratio_quantile_lower = [0, 0.1, 0.2, 0.3]
# dividend_ratio_quantile_lower = [0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7]
# limit = [2, 3, 4, 5, 10]
# lookback_trade_days = [21, 42, 63, 125, 250, 500]
# roe_quantile_lower = [0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6]
# roe_years = [3, 4, 5]
# skip_same_sector = [true, false]
# weight_method = [
#   "equal",
#   "grad(1.2)",
#   "grad(1.5)",
#   "grad(2)",
#   "filter_max(0.9)",
#   "filter_max(0.8)",
#   "filter_max(0.7)",
#   "filter_max(0.6)",
#   "filter_max(0.5)",
# ]

# 目前尖峰规则不能提升策略效果
# [[rules]]
# name = "resize_by_spike"
# frequency = "1d"

# [rules.options]
# spike_days = 2
# spike_fall_threshold = 0.02
# spike_rise_threshold = 0.15

# [rules.search.options]
# spike_days = [1, 2, 3]
# spike_fall_threshold = [0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.08, 0.1]
# spike_rise_threshold = [0.05, 0.06, 0.08, 0.1, 0.12, 0.15, 0.2, 1]
