title = "高质量现金"
description = "持有股息率和自由现金流高的股票"

[[ticker_sources]]
source = "000015.CSI"  # 上证红利
source_type = "index"

[[ticker_sources]]
source = "000922.CSI"  # 中证红利100
source_type = "index"

[[ticker_sources]]
source = "399324.CNI"  # 深证红利
source_type = "index"

[[ticker_sources]]
source = "399411.CNI"  # 国证红利100
source_type = "index"

[[ticker_sources]]
source = "932365.CSI"  # 中证全指自由现金流
source_type = "index"

[[ticker_sources]]
source = "980092.CNI"  # 国证自由现金流
source_type = "index"

[[rules]]
name = "hold_by_real_cash"
frequency = "2m"

[rules.options]
adjust_momentum_weight = 0.8
adjust_roe_weight = 0.8
adjust_volatility_weight = 0
dividend_rank_lower = 0.3
dividend_ratio_lt_lower = 0
free_cash_rank_lower = 0.3
free_cash_ratio_lt_lower = 0.02
free_cash_weight = 0.9
exclude_sectors = ["银行", "非银金融", "房地产", "综合", "公用事业"]
limit = 2
lookback_lt_years = 3
lookback_trade_days = 250
skip_same_sector = false
weight_method = "filter_max(0.8)"

[rules.search]
# frequency = ["1m", "2m", "3m", "6m"]

[rules.search.options]
# adjust_momentum_weight = [0, 0.2, 0.4, 0.6, 0.8, 1, 1.2, 1.4, 1.6, 1.8, 2]
# adjust_roe_weight = [0, 0.2, 0.4, 0.6, 0.8, 1, 1.2, 1.4, 1.6, 1.8, 2]
# adjust_volatility_weight = [0, 0.2, 0.4, 0.6, 0.8, 1, 1.2, 1.4, 1.6, 1.8, 2]
# dividend_rank_lower = [0, 0.1, 0.2, 0.3, 0.4]
# dividend_ratio_lt_lower = [0, 0.01, 0.02]
# free_cash_rank_lower = [0, 0.1, 0.2, 0.3, 0.4]
# free_cash_ratio_lt_lower = [0, 0.01, 0.02]
# free_cash_weight = [0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1]
# limit = [2, 3, 4, 5, 10]
# lookback_lt_years = [1, 2, 3, 4, 5]
# lookback_trade_days = [21, 42, 63, 125, 250, 500]
# skip_same_sector = [true, false]
# weight_method = [
#   "equal",
#   "grad(1.2)",
#   "grad(1.5)",
#   "grad(2)",
#   "filter_max(0.9)",
#   "filter_max(0.8)",
#   "filter_max(0.7)",
#   "filter_max(0.6)",
#   "filter_max(0.5)",
# ]

[[rules]]
name = "resize_by_spike"
frequency = "1d"

[rules.options]
spike_days = 3
spike_fall_threshold = 0.01
spike_rise_threshold = 0.1

[rules.search.options]
# spike_days = [1, 2, 3, 5]
# spike_fall_threshold = [0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.08, 0.1, 0.12, 0.15, 0.2]
# spike_rise_threshold = [0.03, 0.04, 0.05, 0.06, 0.08, 0.1, 0.12, 0.15, 0.2]
