title = "A virtual fund that hold top N stocks by dividend each year"

# Candidate tickers defined with sources
tickers_sources = ["cnindex:399312"]

[[rules]]
name = "hold_topn_equal"
frequency = "1y"

[rules.options]
indicator = "DividendTtm"
limit = 10
sort = "desc"
