title = "A virtual fund that buy all stocks equally at begining and rebalance each year"

# All candidate tickers
tickers = ["688981", "000333"]

[[rules]]
name = "hold_all_equal"
frequency = "1y"


[[rules]]
name = "macd_signal_line_crossover"
frequency = "1d"
