title = "A virtual fund that hold a stock and rebalance by MACD"

# All candidate tickers
tickers = ["688981"]

[[rules]]
name = "hold_all_equal"

[[rules]]
name = "sizing_by_macd_crossover"
frequency = "1d"

[rules.options]
macd_period_fast = 18
macd_period_slow = 36
macd_period_signal = 12
macd_slope_window = 7
rsi_period = 21
