title = "A virtual fund that buy a stock and rebalance by MACD"

# All candidate tickers
tickers = ["688981"]

[[rules]]
name = "hold_all_equal"

[[rules]]
name = "macd_crossover"
frequency = "1d"

[rules.options]
macd_slope_window = 5
