title = "根据基于市场整体PE/PS的估值高低对持有的ETF进行动态调仓"

[tickers]
"510300" = 10 # 沪深300ETF
"159949" = 10 # 创业板50ETF
"513100" = 10 # 纳斯达克100ETF
"513500" = 10 # 标普500ETF
"511260" = 20 # 十年国债ETF
"518880" = 10 # 黄金ETF
"161715" = 10 # 大宗商品LOF


[[rules]]
name = "hold"
frequency = "1y"

[[rules]]
name = "size_by_valuation"
frequency = "4w"

[rules.options]
allow_short = false
lookback_years = 6
pe_quantile_ceil = 0.9
pe_quantile_floor = 0.5
ps_quantile_ceil = 0.8
ps_quantile_floor = 0.2
ticker_watch_index = { "510300" = "000300.csi", "159949" = "399673.cni" }
watch_period_days = 28

[rules.search]
allow_short = [true, false]
lookback_years = [5, 6]
ps_quantile_ceil = [0.7, 0.8]
ps_quantile_floor = [0.2, 0.3]
