title = "小市值"
description = "持有中小板指中市值最小的股票"
options.suspend_months = []  # 大概率过拟合，暂时先不开启 options.suspend_months = [1]

[[ticker_sources]]
source = "399101.CNI"
source_type = "index"

[[rules]]
name = "hold_by_small_cap"
frequency = "1m"

[rules.options]
circulating_ratio_lower = 0.3
limit = 2
pb_quantile_upper = 1
pre_select_ratio = 40
ps_quantile_upper = 0.8
skip_same_sector = true
weight_method = "equal"

[rules.search]
# frequency = ["2w", "1m", "2m", "3m"]

[rules.search.options]
# circulating_ratio_lower = [0, 0.1, 0.2, 0.3, 0.4, 0.5]
# limit = [2, 3, 4, 5]
# pb_quantile_upper = [0.7, 0.8, 0.9, 1]
# pre_select_ratio = [10, 20, 30, 40, 50, 100, 200, 500]
# ps_quantile_upper = [0.7, 0.8, 0.9, 1]
# skip_same_sector = [true, false]

[[rules]]
name = "resize_by_spike"
frequency = "1d"

[rules.options]
spike_days = 2
spike_fall_threshold = 0.1
spike_rise_threshold = 0.2

[rules.search.options]
# spike_days = [1, 2, 3]
# spike_fall_threshold = [0.1, 0.2, 0.3, 0.4, 0.5]
# spike_rise_threshold = [0.1, 0.2, 0.3, 0.4, 0.5, 1]
