title = "持有趋势增强得分最高的ETF"

# tickers = [
#   "510300", # 沪深300
#   "510500", # 中证500
#   "512100", # 中证1000
#   "159915", # 创业板
#   "588000", # 科创50
#   "515790", # 光伏
#   "512480", # 半导体
#   "159825", # 农业
#   "516910", # 物流
#   "159766", # 旅游
#   "159713", # 稀土
#   "515250", # 智能汽车
#   "515400", # 大数据
#   "516510", # 云计算
#   "515750", # 科技50
#   "515950", # 医药龙头
#   "510900", # 恒生H股
#   "513060", # 恒生医疗
#   "513330", # 恒生互联
#   "518880", # 黄金
#   "159985", # 豆粕
#   "511260", # 国债
#   "511220", # 城投债
# ]

tickers = [
  "510300", # 沪深300ETF
  "159949", # 创业板50ETF
  "513100", # 纳斯达克100ETF
  "513500", # 标普500ETF
  "518880", # 黄金ETF
  "511260", # 十年国债ETF
  "161715", # 大宗商品LOF
]

[[rules]]
name = "hold_top_trend"
frequency = "2w"

[rules.options]
limit = 4
lookback_trade_days = 60
regression_alpha = 0.5
regression_test = 0.6

[rules.search]
limit = [3, 4, 5]
lookback_trade_days = [50, 60, 70]
regression_alpha = [0.1, 0.3, 0.5, 0.7, 1.0]
regression_test = [0.5, 0.6, 0.7]
