title = "A virtual fund that hold top N stocks by dividend each year and rebalance by MACD"

# Candidate tickers defined with sources
tickers_sources = ["cnindex:399312"]

[[rules]]
name = "hold_dividend_topn_equal"
frequency = "1y"

[rules.options]
limit = 10
sort = "desc"

[[rules]]
name = "sizing_by_macd_crossover"
frequency = "1d"

[rules.options]
macd_period_fast = 18
macd_period_slow = 36
macd_period_signal = 12
macd_slope_window = 7
rsi_period = 21
