title = "根据MACD对美国ETF进行调仓"

tickers = [
  "513100", # 纳斯达克100ETF
  "513500", # 标普500ETF
  "518880", # 黄金ETF
]

[[rules]]
name = "hold"
frequency = "1y"

[[rules]]
name = "size_by_macd_crossover"
frequency = "1d"

[rules.options]
allow_short = false
macd_period_fast = 24
macd_period_slow = 52
macd_period_signal = 18
macd_slope_window = 5
rsi_period = 21
rsi_low = 40
rsi_high = 60

[rules.search]
frequency = ["3m", "6m", "1y"]
allow_short = [true, false]
macd_period_fast = [12, 24, 30]
macd_period_slow = [26, 52, 60]
macd_period_signal = [9, 18, 20]
macd_slope_window = [3, 5, 7]
# rsi_period = [14, 21, 28]
# rsi_low = [35, 40, 45]
# rsi_high = [55, 60, 65]
